spring:
  datasource:
    url: jdbc:h2:mem:embeadb
    username: embea
    password: password
  h2:
    console.enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    date-format: dd.MM.yyyy
logging:
  level:
    org:
      hibernate:
        SQL: INFO
      type:
        descriptor:
          sql:
          BasicBinder: INFO
debug: false