name: MAIN BUILD

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - '**.yml'
      - '**.gradle'
      - '**.md'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Set up open jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Clone policy-service repo
        uses: actions/checkout@v2

      - name: Build with Gradle
        timeout-minutes: 15
        run: |
          chmod +x gradlew && ./gradlew clean build

      - name: Upload test report
        uses: actions/upload-artifact@v1.0.0
        with:
          name: test-report
          path: build/reports/
